import { Inter } from 'next/font/google';

const nextFont = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <main className={nextFont.className}>{children}</main>
    );
}
